In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [6]:
df = pd.read_csv('../fbuild/ransac_evaluation_results.csv')
df

,iteration,maxIt,threshold,trainPct,minInliers,bestModelCount,numPoints,n,d,noise,...,outlierStrength,saltAndPepper,metric,variation,weighted_average,r2_regression,r2_orthogonal,mse_regression,mse_orthogonal,timeMs
0,1,100,0.1,0.2,100,1,500,2,1,0.0,...,2.5,1,0,1,0,1.000000,1.000000,1.249350e-30,-1.358910e-16,9.37482
1,1,100,0.1,0.2,100,1,500,2,1,0.0,...,2.5,1,0,2,0,1.000000,1.000000,1.249350e-30,-1.358910e-16,7.31667
2,1,100,0.1,0.2,100,1,500,2,1,0.0,...,2.5,1,0,3,0,1.000000,1.000000,1.057170e-20,-4.041210e-17,1.07402
3,2,100,0.1,0.2,100,1,500,2,1,0.0,...,2.5,1,1,1,0,1.000000,1.000000,1.963680e-32,-2.974840e-16,8.54796
4,2,100,0.1,0.2,100,1,500,2,1,0.0,...,2.5,1,1,2,0,1.000000,1.000000,1.963680e-32,-2.974840e-16,8.14019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5659,1887,100,0.1,0.2,100,100,500,32,31,0.5,...,2.5,0,0,2,0,-64.330400,0.980306,9.504920e+01,7.595500e-01,31.79750
5660,1887,100,0.1,0.2,100,100,500,32,31,0.5,...,2.5,0,0,3,0,0.337643,0.977635,9.636630e-01,8.625480e-01,10.45860
5661,1888,100,0.1,0.2,100,100,500,32,31,0.5,...,2.5,0,1,1,0,-673.328000,0.981605,8.016620e+02,6.929100e-01,26.16120
5662,1888,100,0.1,0.2,100,100,500,32,31,0.5,...,2.5,0,1,2,0,-16.224000,0.977586,2.047650e+01,8.442810e-01,26.90830
5663,1888,100,0.1,0.2,100,100,500,32,31,0.5,...,2.5,0,1,3,0,0.133364,0.975576,1.030280e+00,9.199980e-01,13.33360

In [7]:
metrics_map = {
    0: 'R2',
    1: 'MSE',
}

variation_map = {
    1: 'MeanSDF',
    2: 'MedianSDF',
    3: 'HuberRegression'
}

In [8]:
df_group = df.groupby(['variation', 'metric'])[['r2_regression', 'r2_orthogonal', 'mse_regression', 'mse_orthogonal']].mean().reset_index()
df_group

,variation,metric,r2_regression,r2_orthogonal,mse_regression,mse_orthogonal
0,1,0,-5.240838e+04,0.932442,2.049064e+04,0.436194
1,1,1,-1.545320e+04,0.938220,6.087483e+03,0.437974
2,2,0,-2.155623e+07,0.948523,1.492480e+07,0.415900
3,2,1,-1.609507e+04,0.934351,1.040886e+04,0.444371
4,3,0,-4.621814e-01,0.905277,7.260754e-01,0.527336
5,3,1,-3.816309e-01,0.903216,7.311639e-01,0.525271